version: '3.8'

volumes:
  tg_bot_postgres_data: {}
  tg_bot_postgres_data_backups: {}
  static_data: {}

networks:
  tg_bot_network:

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: tg_bot_django_image:latest
    container_name: tg_bot_django_container
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_data:/app/vol
      - ./app/:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - tg_bot_network

  postgres:
    image: postgres:15.5-alpine3.18
    container_name: tg_bot_postgres_container
    restart: unless-stopped
    volumes:
      - tg_bot_postgres_data:/var/lib/postgresql/data:Z
      - tg_bot_postgres_data_backups:/backups:z
    env_file:
      - ./.env
    networks:
      - tg_bot_network
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432

  redis:
    image: redis:alpine3.18
    container_name: tg_bot_redis_container
    restart: unless-stopped
    networks:
      - tg_bot_network
    expose:
      - "6379"
    ports:
      - "6379:6379"